[package]
name = "ramenon"
version = "0.1.0"
edition = "2021"
description = "Roman numerals converter"
repository = "https://github.com/mdmundo/ramenon/"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
